# Docker Compose pour développement/test local (Preprod)

services:
  # Base de données PostgreSQL pour tests
  db:
    image: postgres:15-alpine
    container_name: yanotela-db-local
    environment:
      POSTGRES_USER: yanotela_local
      POSTGRES_PASSWORD: yanotela_local_2024
      POSTGRES_DB: yanotela_local
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yanotela_local -d yanotela_local"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Redis pour les sessions (optionnel en local)
  redis:
    image: redis:7-alpine
    container_name: yanotela-redis-local
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Backend Node.js/Express
  backend:
    build: 
      context: ./Server
      dockerfile: Dockerfile.preprod
    container_name: yanotela-backend-local
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://yanotela_local:yanotela_local_2024@db:5432/yanotela_local
      - REDIS_URL=redis://redis:6379
      - CLIENT_URL=http://localhost:3000
      - SESSION_SECRET=local_session_secret_dev_only
      - MAIL_SERVICE=gmail
      - MAIL_USER=test@example.com
      - MAIL_PASSWORD=test_password
    volumes:
      # Mount source code for hot reload
      - ./Server/src:/app/src
      - ./Server/prisma:/app/prisma
      - ./Server/package.json:/app/package.json
      - ./Server/package-lock.json:/app/package-lock.json
      - ./Server/jest.config.json:/app/jest.config.json
      - ./Server/index.js:/app/index.js
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npx nodemon index.js"

  # Frontend Next.js
  frontend:
    build: 
      context: ./Client
      dockerfile: Dockerfile.preprod
    container_name: yanotela-frontend-local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      # Mount source code for hot reload
      - ./Client/src:/app/src
      - ./Client/public:/app/public
      - ./Client/package.json:/app/package.json
      - ./Client/package-lock.json:/app/package-lock.json
      - ./Client/next.config.ts:/app/next.config.ts
      - ./Client/tailwind.config.ts:/app/tailwind.config.ts
      - ./Client/postcss.config.mjs:/app/postcss.config.mjs
      - ./Client/tsconfig.json:/app/tsconfig.json
      - ./Client/eslint.config.mjs:/app/eslint.config.mjs
      # Exclude node_modules and .next to avoid conflicts
      - /app/node_modules
      - /app/.next
      - /app/.next
    depends_on:
      - backend

volumes:
  postgres_local_data:
    driver: local