#!/bin/bash

# Script de test des corrections de collaboration

echo "🧪 Test des corrections de collaboration temps réel"
echo "=================================================="
echo ""

# Vérifier si Docker est disponible
if command -v docker &> /dev/null; then
    echo "✅ Docker détecté"
    echo ""
    echo "Option 1: Redémarrer avec Docker"
    echo "  docker compose -f docker-compose.dev.yml down"
    echo "  docker compose -f docker-compose.dev.yml up --build"
    echo ""
else
    echo "⚠️ Docker non détecté"
    echo ""
fi

echo "Option 2: Redémarrage manuel"
echo "----------------------------"
echo ""
echo "Terminal 1 (Serveur):"
echo "  cd Server"
echo "  npm run dev"
echo ""
echo "Terminal 2 (Client):"
echo "  cd Client"
echo "  npm run dev"
echo ""
echo "=================================================="
echo ""
echo "📝 Instructions de test:"
echo ""
echo "1. Ouvrir http://localhost:3000 dans le navigateur 1"
echo "2. Se connecter et ouvrir une note"
echo "3. Ouvrir http://localhost:3000 dans le navigateur 2 (mode incognito)"
echo "4. Se connecter avec un autre compte et ouvrir la MÊME note"
echo "5. Taper du texte en même temps dans les 2 navigateurs"
echo ""
echo "✅ Vérifications attendues:"
echo "  - Le curseur NE doit PAS se déplacer automatiquement"
echo "  - 'Utilisateur écrit...' doit s'afficher pour l'AUTRE utilisateur"
echo "  - Les modifications doivent apparaître en temps réel"
echo "  - Pas de boucles infinies dans la console"
echo ""
echo "=================================================="
echo ""
echo "🔍 Logs à surveiller:"
echo ""
echo "Dans la console navigateur (F12):"
echo "  ✅ Pas d'erreur 'socket introuvable'"
echo "  ✅ Pas de boucles de messages"
echo "  ✅ Messages 'Applying remote update' suivis de 'Remote update complete'"
echo ""
echo "Dans les logs serveur:"
echo "  ✅ Messages 'User X connecté à la note'"
echo "  ✅ Pas de spam de 'contentUpdate'"
echo "  ✅ Sauvegardes BDD espacées de 1+ seconde"
echo ""
echo "=================================================="
