name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      working-directory: Server

    - name: Write SSH key to file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > my_key.pem
        chmod 600 my_key.pem

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key_path: my_key.pem
        source: "./"  # This now correctly points to the current directory
        target: "/var/www/Yanotela"

    - name: Restart PM2 application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key_path: my_key.pem
        script: |
          cd /var/www/Yanotela
          pm2 reload all  # This command restarts your application

    - name: Remove temporary SSH key
      run: rm -f my_key.pem
